# Generated by Django 5.0.4 on 2024-04-11 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2024, 4, 11, 22, 3, 28, 387105)),
        ),
    ]
